package com.maventech.cryptoapp.model.order

import com.google.gson.annotations.SerializedName

data class OrderItem (

	@SerializedName("customerID") val customerID : Int,
	@SerializedName("orderID") val orderID : Int,
	@SerializedName("loginId") val loginId : String,
	@SerializedName("password") val password : String,
	@SerializedName("secondaryEmail") val secondaryEmail : String,
	@SerializedName("name") val name : String,
	@SerializedName("phoneNumber") val phoneNumber : String,
	@SerializedName("countryID") val countryID : Int,
	@SerializedName("country") val country : String,
	@SerializedName("timezoneID") val timezoneID : String,
	@SerializedName("timeZone") val timeZone : String,
	@SerializedName("timeZoneHours") val timeZoneHours : String,
	@SerializedName("educationLevelID") val educationLevelID : Int,
	@SerializedName("educationalLevel") val educationalLevel : String,
	@SerializedName("productID") val productID : Int,
	@SerializedName("product") val product : String,
	@SerializedName("deadlineID") val deadlineID : Int,
	@SerializedName("deadline") val deadline : String,
	@SerializedName("standardID") val standardID : Int,
	@SerializedName("standard") val standard : String,
	@SerializedName("numberofPages") val numberofPages : Int,
	@SerializedName("subject") val subject : String,
	@SerializedName("topic") val topic : String,
	@SerializedName("instructions") val instructions : String,
	@SerializedName("styleofWork") val styleofWork : String,
	@SerializedName("language") val language : String,
	@SerializedName("requiredRefrences") val requiredRefrences : String,
	@SerializedName("fontType") val fontType : String,
	@SerializedName("sapcing") val sapcing : String,
	@SerializedName("attachedFile") val attachedFile : String,
	@SerializedName("totalPrice") val totalPrice : Double,
	@SerializedName("paidPrice") val paidPrice : Double,
	@SerializedName("discount") val discount : Double,
	@SerializedName("discountPercentage") val discountPercentage : String,
	@SerializedName("discountCode") val discountCode : String,
	@SerializedName("orderDate") val orderDate : String,
	@SerializedName("orderDilveryDate") val orderDilveryDate : String,
	@SerializedName("refrenceUser") val refrenceUser : String,
	@SerializedName("site") val site : String,
	@SerializedName("paymentID") val paymentID : String,
	@SerializedName("noofWords") val noofWords : Int
)